---
title: "DESeq2ToTopGO_spruce"
output: html_document
date: "2025-12-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/projects/eco_genomics_2025/final_project/mydata")
```

## DESeq2 To TopGO:

Import libraries and data:
```{r}
library(topGO)
library(GO.db)
library(tidyverse)

z <- read.table("/gpfs1/cl/ecogen/pbio6800/PopulationGenomics/ref_genome/Pmariana/annotation/GO_annotations/Pmariana_GO_annotations_sorted_join.txt", header=F, fill=T)
PmGOannot <- z %>% mutate(V7=ifelse(V7 %in% "", V2,V7))
colnames(PmGOannot) <- c("gene", "start", "stop", "geneID", "strand", "parent", "marker")

PmGOannot$geneID <- gsub('ID=', '', PmGOannot$geneID)
```

** Keep on getting this: "Warning :No enrichment can pe performed - there are no feasible GO terms!" ??? **

1. Functional enrichment for CoolWet - Control vs. Heat
```{r}
# Convert to data frame
coolwetCvsH_df <- as.data.frame(coolwetCvsH) # reading in results from DESeq2 into a dataframe 

# Add geneID column from rownames
coolwetCvsH_df$geneID <- rownames(coolwetCvsH) # pulling out rownames from coolwetCvsH dataframe
coolwetCvsH_df <- coolwetCvsH_df[, c("geneID", setdiff(names(coolwetCvsH_df), "geneID"))] # change column name to geneID

# Read GO terms file
spruce_go <- read.delim("Pmariana_GOannot.tsv", header = TRUE) %>% #reading in GO terms file
  slice(-c(1,2)) %>%  # remove header rows if present
  na.omit()  # remove missing GO annotations

coolwetCvsH_merge <- merge(coolwetCvsH_df, PmGOannot, by = c("geneID", "geneID")) # merging the coolwetCvsH_df with PmGOannot together by geneID

# Identify DEGs that have GO annotations
cwCvsH_GO <- coolwetCvsH_merge[coolwetCvsH_merge$gene %in% spruce_go$geneID, ]

# Keep only significant DEGs 
cwCvsH_GO_sig <- subset(cwCvsH_GO, padj < 0.05 & abs(log2FoldChange) > 1)

# Merge with GO annotations
# cwCvsH_stat <- merge(cwCvsH_GO_sig, cwCvsH_GO)

cwCvsH_stat <- merge(cwCvsH_GO_sig, cwCvsH_GO) #try to run functional enrichment without subsetting significant DEGs

# Create gene2GO list which is used in the topgo function 
cwCvsH_gene2GO <- spruce_go %>%
  filter(!is.na(GO) & GO != "") %>%
  group_by(geneID) %>%
  summarise(GO = list(unique(GO)), .groups = "drop") %>%
  with(setNames(GO, geneID))

# Split semicolon-separated GO terms
cwCvsH_gene2GO <- lapply(cwCvsH_gene2GO, function(x) unlist(strsplit(x, ";")))

# Create geneList for TopGO: 1 = DEG, 0 = not DEG
cwCvsH_allgenes <- names(cwCvsH_gene2GO)
cwCvsH_geneList <- setNames(as.integer(cwCvsH_allgenes %in% cwCvsH_stat$gene), cwCvsH_allgenes)

#Build TopGO pipeline 
cwCvsH_GOdata <- new("topGOdata",
              description = "CoolWet: Control vs. Heat DEGs GO enrichment",
              ontology = "BP",
              allGenes = cwCvsH_geneList,
              geneSel = function(x) x == 1,
              nodeSize = 5,
              annot = annFUN.gene2GO,
              gene2GO = cwCvsH_gene2GO)

#test for enrichment 
cwCvsH_result <- runTest(cwCvsH_GOdata, algorithm = "parentChild", statistic = "fisher")
```

2. Functional enrichment for CoolWet - Control vs. Heat
```{r}
# Convert to data frame
coolwetCvsDH_df <- as.data.frame(coolwetCvsDH) # reading in results from DESeq2 into a dataframe 

# Add geneID column from rownames
coolwetCvsDH_df$geneID <- rownames(coolwetCvsDH) # pulling out rownames from coolwetCvsH dataframe
coolwetCvsDH_df <- coolwetCvsDH_df[, c("geneID", setdiff(names(coolwetCvsDH_df), "geneID"))] # change column name to geneID

# Read GO terms file
spruce_go <- read.delim("Pmariana_GOannot.tsv", header = TRUE) %>% #reading in GO terms file
  slice(-c(1,2)) %>%  # remove header rows if present
  na.omit()  # remove missing GO annotations

coolwetCvsDH_merge <- merge(coolwetCvsDH_df, PmGOannot, by = c("geneID", "geneID")) # merging the coolwetCvsH_df with PmGOannot together by geneID

# Identify DEGs that have GO annotations
cwCvsDH_GO <- coolwetCvsDH_merge[coolwetCvsDH_merge$gene %in% spruce_go$geneID, ]

# Keep only significant DEGs 
cwCvsDH_GO_sig <- subset(cwCvsDH_GO, padj < 0.05 & abs(log2FoldChange) > 1)

# Merge with GO annotations
# cwCvsH_stat <- merge(cwCvsH_GO_sig, cwCvsH_GO)

cwCvsDH_stat <- merge(cwCvsDH_GO_sig, cwCvsDH_GO) #try to run functional enrichment without subsetting significant DEGs

# Create gene2GO list which is used in the topgo function 
cwCvsDH_gene2GO <- spruce_go %>%
  filter(!is.na(GO) & GO != "") %>%
  group_by(geneID) %>%
  summarise(GO = list(unique(GO)), .groups = "drop") %>%
  with(setNames(GO, geneID))

# Split semicolon-separated GO terms
cwCvsDH_gene2GO <- lapply(cwCvsDH_gene2GO, function(x) unlist(strsplit(x, ";")))

# Create geneList for TopGO: 1 = DEG, 0 = not DEG
cwCvsDH_allgenes <- names(cwCvsDH_gene2GO)
cwCvsDH_geneList <- setNames(as.integer(cwCvsDH_allgenes %in% cwCvsDH_stat$gene), cwCvsDH_allgenes)

#Build TopGO pipeline 
cwCvsDH_GOdata <- new("topGOdata",
              description = "CoolWet: Control vs. Heat DEGs GO enrichment",
              ontology = "BP",
              allGenes = cwCvsDH_geneList,
              geneSel = function(x) x == 1,
              nodeSize = 5,
              annot = annFUN.gene2GO,
              gene2GO = cwCvsDH_gene2GO)

#test for enrichment 
cwCvsDH_result <- runTest(cwCvsDH_GOdata, algorithm = "parentChild", statistic = "fisher")
```